config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/courses", to: "static_pages#courses"
  get "/news", to: "static_pages#news"
  get "/news_post", to: "static_pages#news_post"
  get "/teachers", to: "static_pages#teachers"
  get "/register", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    before_save {email.downcase!}
    before_save:default_value
    validates :username, presence: true, length: {maximum: Settings.users.max_name}, uniqueness: {case_sensitive: false}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: Settings.users.max_email},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
    has_secure_password
    validates :password, presence:true, length: {minimum: Settings.users.min_pass}
    def default_value
        self.is_active= true
        self.is_admin = false
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def about; end

  def contact; end

  def courses; end

  def news; end

  def news_post; end

  def teachers; end

  def login; end

  def signup; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i(index edit update)
  before_action :correct_user, only: %i(edit update)

  def index
    @user = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new user_params
    if @user.save
      login_url @user
      flash[:success]= "Register success"
      redirect_to @user
    else
      render :new
    end
  end

  private
  def set_user
    @user = User.find_by params[:id]
  end

  def user_params
    params.require(:user).permit :user_id, :name, :username, :email, :password, :password_confirmation, :birthdate, :is_admin, :is_active
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="newsletter">
        <div class="row">
          <div class="col">
            <div class="section_title text-center">
              <h1><%= t ".sub_new" %></h1>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col text-center">
            <div class="newsletter_form_container mx-auto">
              <form action="post">
                <div class="newsletter_form d-flex flex-md-row flex-column flex-xs-column align-items-center justify-content-center">
                  <input id="newsletter_email" class="newsletter_email" type="email" placeholder="Email Address" required="required" data-error="Valid email is required.">
                  <button id="newsletter_submit" type="submit" class="newsletter_submit_btn trans_300" value="Submit"><%= t ".sub" %></button>
                </div>
              </form>
            </div>
          </div>
        </div>
    </div>
      <div class="footer_content">
        <div class="row">
          <div class="col-lg-3 footer_col">
            <div class="logo_container">
              <div class="logo">
                <span><%= t ".uni" %></span>
              </div>
            </div>
            <p class="footer_about_text"><%= t ".in" %></p>
          </div>
          <div class="col-lg-3 footer_col">
            <div class="footer_column_title"><%= t ".menu" %></div>
            <div class="footer_column_content">
              <ul>
                <li class="menu_item menu_mm"><%= link_to "Home", root_path %></li>
                  <li class="menu_item menu_mm"><%= link_to "About", about_path %></li>
                <li class="menu_item menu_mm"><%= link_to "Courses", courses_path %></li>
                <li class="menu_item menu_mm"><%= link_to "News", news_path %></li>
                <li class="menu_item menu_mm"><%= link_to "Contact", contact_path %></li></a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 footer_col">
            <div class="footer_column_title"><%= t ".use" %></div>
            <div class="footer_column_content">
              <ul>
                <li class="footer_list_item"><a href="#"><%= t ".tes" %></a></li>
                <li class="footer_list_item"><a href="#"><%= t ".faq" %></a></li>
                <li class="footer_list_item"><a href="#"><%= t ".com" %></a></li>
                <li class="footer_list_item"><a href="#"><%= t ".cam" %></a></li>
                <li class="footer_list_item"><a href="#"><%= t ".tui" %></a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 footer_col">
            <div class="footer_column_title"><%= t ".contact" %></div>
            <div class="footer_column_content">
              <ul>
                <li class="footer_contact_item">
                  <div class="footer_contact_icon">
                    <%= link_to image_tag("placeholder.svg", alt: "") %>
                  </div>
                  Blvd Libertad, 34 m05200 Arévalo
                </li>
                <li class="footer_contact_item">
                  <div class="footer_contact_icon">
                    <%= link_to image_tag("smartphone.svg", alt: "") %>
                  </div>
                  0034 37483 2445 322
                </li>
                <li class="footer_contact_item">
                  <div class="footer_contact_icon">
                    <%= link_to image_tag("envelope.svg", alt: "") %>
                  </div>hello@company.com
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="footer_bar d-flex flex-column flex-sm-row align-items-center">
        <div class="footer_copyright">
          <span><%= t ".copy" %> &copy;<%= t ".right" %><a href="https://colorlib.com" target="_blank">Colorlib</a></span>
        </div>
      </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header d-flex flex-row">
  <div class="header_content d-flex flex-row align-items-center">
    <div class="logo_container">
      <div class="logo">
        <%= link_to image_tag("logo.png", alt: "") %>
      </div>
    </div>
    <nav class="main_nav_container">
      <div class="main_nav">
        <ul class="main_nav_list">
          <li class="main_nav_item"><%= link_to "Home", root_url %></li>
          <li class="main_nav_item"><%= link_to "About", about_path %></li>
          <li class="main_nav_item"><%= link_to "Courses", courses_path %></li>
          <li class="main_nav_item"><%= link_to "News", news_path %></li>
          <li class="main_nav_item"><%= link_to "Contact", contact_path %></li>
          <li class="main_nav_item"><%= link_to "Login", sessions_new_path %></li>
          <li class="main_nav_item"><%= link_to "Register", register_path %></li>
        </ul>
      </div>
    </nav>
  </div>
  <div class="header_side d-flex flex-row justify-content-center align-items-center">
    <%= link_to image_tag("phone-call.svg", alt: "") %>
    <span>+43 4566 7788 2457</span>
  </div>
  <div class="hamburger_container">
    <i class="fas fa-bars trans_200"></i>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?String %>
    <div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Project" %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <header>
    <%= render "layouts/header" %>
    </header>
    <main role="main">
       <%= render "layouts/messages" %>
       <%= yield %>
    </main>
    <footer>
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= pluralize @user.errors.count, "error" %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<div class="super_container">
  <div class="menu_container menu_mm">
    <div class="menu_close_container">
      <div class="menu_close"></div>
    </div>
  </div>
  <div class="home">
    <div class="home_background_container prlx_parent">
      <div class="home_background prlx" style="background-image">
        <%= link_to image_tag("slider_background.jpg", alt: "") %>
      </div>
    </div>
    <div class="home_content">
      <h1><%= t ".about" %></h1>
    </div>
  </div>
  <div class="aboutus">
    <div class="about_title" align="center"><%= t ".about_the" %></div>
    <p class="about_text"><%= t ".ox" %></p>
    <%= link_to image_tag("about.jpg", alt: "") %>
    <div class="contact_info">
      <ul>
        <li class="contact_info_item">
          <div class="contact_info_icon">
          <%= link_to image_tag("placeholder.svg", alt: ""), "https://www.flaticon.com/authors/lucy-g"%>
          </div>
          Blvd Libertad, 34 m05200 Arévalos
        </li>
        <li class="contact_info_item">
          <div class="contact_info_icon">
            <%= link_to image_tag("smartphone.svg", alt: ""), "https://www.flaticon.com/authors/lucy-g"  %>
          </div>
          0034 37483 2445 322
        </li>
        <li class="contact_info_item">
          <div class="contact_info_icon">
            <%= link_to image_tag("envelope.svg", alt: ""), "https://www.flaticon.com/authors/lucy-g" %>
          </div>hello@company.com
        </li>
      </ul>
    </div>
  </div>

app/views/static_pages/contact.html.erb
<div class="super_container">
  <div class="menu_container menu_mm">
    <div class="menu_close_container">
      <div class="menu_close"></div>
    </div>
  </div>
  <div class="home">
    <div class="home_background_container prlx_parent">
      <div class="home_background prlx" style="background-image"><%= link_to image_tag("slider_background.jpg", alt: "") %></div>
    </div>
    <div class="home_content">
      <h1><%= t ".contact" %></h1>
    </div>
  </div>
  <div class="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="contact_form">
            <div class="contact_title"><%= t ".get" %></div>
            <div class="contact_form_container">
              <form action="post">
                <input id="contact_form_name" class="input_field contact_form_name" type="text" placeholder="Name" required="required" data-error="Name is required.">
                <input id="contact_form_email" class="input_field contact_form_email" type="email" placeholder="E-mail" required="required" data-error="Valid email is required.">
                <textarea id="contact_form_message" class="text_field contact_form_message" name="message" placeholder="Message" required="required" data-error="Please, write us a message."></textarea>
                <button id="contact_send_btn" type="button" class="contact_send_btn trans_200" value="Submit"><%= t ".send" %></button>
              </form>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="about">
            <div class="about_title"><%= t ".join" %></div>
            <p class="about_text"><%= t ".in" %></p>
            <div class="contact_info">
              <ul>
                <li class="contact_info_item">
                  <div class="contact_info_icon">
                  <%= link_to image_tag("placeholder.svg", alt: ""), "https://www.flaticon.com/authors/lucy-g"%>
                  </div>
                  Blvd Libertad, 34 m05200 Arévalo
                </li>
                <li class="contact_info_item">
                  <div class="contact_info_icon">
                    <%= link_to image_tag("smartphone.svg", alt: ""), "https://www.flaticon.com/authors/lucy-g"  %>
                  </div>
                  0034 37483 2445 322
                </li>
                <li class="contact_info_item">
                  <div class="contact_info_icon">
                    <%= link_to image_tag("envelope.svg", alt: ""), "https://www.flaticon.com/authors/lucy-g" %>
                  hello@company.com
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <div id="google_map">
            <div class="map_container">
              <div id="map"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/courses.html.erb
<div class="super_container">
  <div class="menu_container menu_mm">
    <div class="menu_close_container">
      <div class="menu_close"></div>
    </div>
  </div>
  <div class="home">
    <div class="home_background_container prlx_parent">
      <div class="home_background prlx" style="background-image"><%= link_to image_tag("courses_background.jpg", alt: "") %></div>
    </div>
    <div class="home_content">
      <h1><%= t ".course" %></h1>
    </div>
  </div>
  <div class="popular page_section">
    <div class="container">
      <div class="row">
        <div class="col">
          <div class="section_title text-center">
            <h1><%= t ".popular" %></h1>
          </div>
        </div>
      </div>
      <div class="row course_boxes">
        <div class="col-lg-4 course_box">
          <div class="card">
            <div class="card-img-top"><%= link_to image_tag("course_1.jpg", alt: ""), "https://unsplash.com/@kellybrito" %></div>
            <div class="card-body text-center">
              <div class="card-title"><a href="courses.html.erb"><%= t ".a" %></a></div>
              <div class="card-text"><%= t ".adobe" %></div>
            </div>
            <div class="price_box d-flex flex-row align-items-center">
              <div class="course_author_image">
                <%= link_to image_tag("author.jpg", alt: ""), "https://unsplash.com/@mehdizadeh" %>
              </div>
              <div class="course_author_name">Michael Smith</div>
              <div class="course_price d-flex flex-column align-items-center justify-content-center">&nbsp;<span>$29</span>&nbsp;</div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 course_box">
          <div class="card">
            <div class="card-img-top"><%= link_to image_tag("course_2.jpg", alt: ""), "https://unsplash.com/@cikstefan" %></div>
            <div class="card-body text-center">
              <div class="card-title"><a href="courses.html.erb"><%= t ".begin" %></a></div>
              <div class="card-text"><%= t ".adobe" %></div>
            </div>
            <div class="price_box d-flex flex-row align-items-center">
              <div class="course_author_image">
                <%= link_to image_tag("author.jpg", alt: ""), "https://unsplash.com/@mehdizadeh" %>
              </div>
              <div class="course_author_name">Michael Smith</div>
              <div class="course_price d-flex flex-column align-items-center justify-content-center">&nbsp;<span>$29</span>&nbsp;</div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 course_box">
          <div class="card">
            <div class="card-img-top"><%= link_to image_tag("course_3.jpg", alt: ""), "https://unsplash.com/@dsmacinnes" %></div>
            <div class="card-body text-center">
              <div class="card-title"><a href="courses.html.erb"><%= t ".ad" %></a></div>
              <div class="card-text"><%= t ".adobe" %></div>
            </div>
            <div class="price_box d-flex flex-row align-items-center">
              <div class="course_author_image">
                <%= link_to image_tag("author.jpg", alt: ""), "https://unsplash.com/@mehdizadeh" %>
              </div>
              <div class="course_author_name">Michael Smith</div>
              <div class="course_price d-flex flex-column align-items-center justify-content-center">&nbsp;<span><%= t ".hello" %></span>&nbsp;</div>
            </div>
          </div>
        </div>
      </div><%= t ".ad" %>
      <div class="row course_boxes">
        <div class="col-lg-4 course_box">
          <div class="card">
            <div class="card-img-top"><%= link_to image_tag("course_7.jpg", alt: ""), "https://unsplash.com/@gaellemm" %></div>
            <div class="card-body text-center">
              <div class="card-title"><a href="courses.html.erb"><%= t ".a" %></a></div>
              <div class="card-text"><%= t ".adobe" %></div>
            </div>
            <div class="price_box d-flex flex-row align-items-center">
              <div class="course_author_image">
                <%= link_to image_tag("author.jpg", alt: ""), "https://unsplash.com/@mehdizadeh" %>
              </div>
              <div class="course_author_name">Michael Smith</div>
              <div class="course_price d-flex flex-column align-items-center justify-content-center">&nbsp;<span>$29</span>&nbsp;</div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 course_box">
          <div class="card">
            <div class="card-img-top"><%= link_to image_tag("course_8.jpg", alt: ""), "https://unsplash.com/@juanmramosjr" %></div>
            <div class="card-body text-center">
              <div class="card-title"><a href="courses.html.erb"><%= t ".begin" %></a></div>
              <div class="card-text"><%= t ".adobe" %></div>
            </div>
            <div class="price_box d-flex flex-row align-items-center">
              <div class="course_author_image">
                <%= link_to image_tag("author.jpg", alt: ""), "https://unsplash.com/@mehdizadeh" %>
              </div>
              <div class="course_author_name">Michael Smith</div>
              <div class="course_price d-flex flex-column align-items-center justify-content-center">&nbsp;<span>$29</span>&nbsp;</div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 course_box">
          <div class="card">
            <div class="card-img-top"><%= link_to image_tag("course_9.jpg", alt: ""), "https://unsplash.com/@kimberlyfarmer" %></div>
            <div class="card-body text-center">
              <div class="card-title"><a href="courses.html.erb"><%= t ".ad" %></a></div>
              <div class="card-text"><%= t ".adobe" %></div>
            </div>
            <div class="price_box d-flex flex-row align-items-center">
              <div class="course_author_image">
                <%= link_to image_tag("author.jpg", alt: ""), "https://unsplash.com/@mehdizadeh" %>
              </div>
              <div class="course_author_name">Michael Smith</div>
              <div class="course_price d-flex flex-column align-items-center justify-content-center">&nbsp;<span>$29</span>&nbsp;</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/teachers.html.erb
<div class="super_container">
  <div class="menu_container menu_mm">
    <div class="menu_close_container">
      <div class="menu_close"></div>
    </div>
  </div>
  <div class="home">
    <div class="home_background_container prlx_parent">
      <div class="home_background prlx" style="background-image"><%= link_to image_tag("teachers_background", alt: "") %></div>
    </div>
    <div class="home_content">
      <h1><%= t ".teacher" %></h1>
    </div>
  </div>
  <div class="teachers page_section">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 teacher">
          <div class="card">
            <div class="card_img">
              <div class="card_plus trans_200 text-center"><a href="#">+</a></div>
              <div class="card-img-top trans_200"><%= link_to image_tag("teacher_1.jpg", alt: ""), "https://unsplash.com/@michaeldam" %></div>
            </div>
            <div class="card-body text-center">
              <div class="card-title"><a href="#">Maria Smith</a></div>
              <div class="card-text"><%= t ".graph" %></div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 teacher">
          <div class="card">
            <div class="card_img">
              <div class="card_plus trans_200 text-center"><a href="#">+</a></div>
              <div class="card-img-top trans_200"><%= link_to image_tag("teacher_2.jpg", alt: ""), "https://unsplash.com/@jcpeacock" %></div>
            </div>
            <div class="card-body text-center">
              <div class="card-title"><a href="#">Christian Blue</a></div>
              <div class="card-text"><%= t ".graph" %></div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 teacher">
          <div class="card">
            <div class="card_img">
              <div class="card_plus trans_200 text-center"><a href="#">+</a></div>
              <img class="card-img-top trans_200"><%= link_to image_tag("teacher_3.jpg", alt: ""), "https://unsplash.com/photos/n8jeOSxCRfQ" %></div>
            </div>
            <div class="card-body text-center">
              <div class="card-title"><a href="#">James Brown</a></div>
              <div class="card-text"><%= t ".graph" %></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="milestones">
    <div class="milestones_background" style="background-image"><%= link_to image_tag("milestones_background.jpg", alt: "") %></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-3 milestone_col">
          <div class="milestone text-center">
            <div class="milestone_icon"><%= link_to image_tag("milestone_1.svg", alt: ""), "https://www.flaticon.com/authors/zlatko-najdenovski" %></div>
            <div class="milestone_counter" data-end-value="750">0</div>
            <div class="milestone_text"><%= t ".current" %></div>
          </div>
        </div>
        <div class="col-lg-3 milestone_col">
          <div class="milestone text-center">
            <div class="milestone_icon"><%= link_to image_tag("milestone_2.svg", alt: ""), "https://www.flaticon.com/authors/zlatko-najdenovski" %></div>
            <div class="milestone_counter" data-end-value="120">0</div>
            <div class="milestone_text"><%= t ".cer" %></div>
          </div>
        </div>
        <div class="col-lg-3 milestone_col">
          <div class="milestone text-center">
            <div class="milestone_icon"><%= link_to image_tag("milestone_3.svg", alt: ""), "https://www.flaticon.com/authors/zlatko-najdenovski" %></div>
            <div class="milestone_counter" data-end-value="39">0</div>
            <div class="milestone_text"><%= t ".app" %></div>
          </div>
        </div>
        <div class="col-lg-3 milestone_col">
          <div class="milestone text-center">
            <div class="milestone_icon"><%= link_to image_tag("milestone_4.svg", alt: ""), "https://www.flaticon.com/authors/zlatko-najdenovski" %></div>
            <div class="milestone_counter" data-end-value="3500" data-sign-before="+">0</div>
            <div class="milestone_text"><%= t ".gra" %></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="become">
    <div class="container">
      <div class="row row-eq-height">
        <div class="col-lg-6 order-2 order-lg-1">
          <div class="become_title">
            <h1><%= t ".become" %></h1>
          </div>
          <p class="become_text"><%= t ".in" %></p>
          <div class="become_button text-center trans_200">
            <a href="#"><%= t ".read" %></a>
          </div>
        </div>
        <div class="col-lg-6 order-1 order-lg-2">
          <div class="become_image">
            <%= link_to image_tag("become.jpg", alt: "") %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="super_container">
  <div class="menu_container menu_mm">
    <div class="menu_close_container">
      <div class="menu_close"></div>
    </div>
  </div>
  <div class="home">
    <div class="home_background_container prlx_parent">
      <div class="home_background prlx" style="background-image"><%= link_to image_tag("slider_background.jpg", alt: "") %></div>
    </div>
    <div class="home_content">
      <h1>Sign Up</h1>
    </div>
  </div>
  <div class="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="contact_form">
            <div class="contact_title"><%= t ".signup" %></div>
            <div class="contact_form_container">
              <div class="name-group">
                <%= form_for(@user) do |f| %>
                <%= render 'shared/error_messages' %>
                <%= f.label :username %>
                <%= f.text_field :username, class: 'form-control' %>
                <%= f.label :email %>
                <%= f.email_field :email, class: 'form-control' %>
                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control' %>
                <%= f.label :password_confirmation, "Confirmation" %>
                <%= f.password_field :password_confirmation, class: 'form-control' %>
                <%= f.submit "Create my account", class: "contact_send_btn trans_200" %>
                  <% end %>
              </div>
                  <span><%= t ".al" %></span><%= link_to "Login", sessions_new_path %>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="about">
            <div class="about_title"><%= t ".join" %></div>
            <p class="about_text"><%= t ".in" %></p>
            <div class="contact_info">
              <ul>
                <li class="contact_info_item">
                  <div class="contact_info_icon">
                  <%= link_to image_tag("placeholder.svg", alt: ""), "https://www.flaticon.com/authors/lucy-g"%>
                  </div>
                  Blvd Libertad, 34 m05200 Arévalo
                </li>
                <li class="contact_info_item">
                  <div class="contact_info_icon">
                    <%= link_to image_tag("smartphone.svg", alt: ""), "https://www.flaticon.com/authors/lucy-g"  %>
                  </div>
                  0034 37483 2445 322
                </li>
                <li class="contact_info_item">
                  <div class="contact_info_icon">
                    <%= link_to image_tag("envelope.svg", alt: ""), "https://www.flaticon.com/authors/lucy-g" %>
                  </div>hello@company.com
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <div id="google_map">
            <div class="map_container">
              <div id="map"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>